CREATE TABLE leave_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    personal_number VARCHAR(20) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    leave_type VARCHAR(50) NOT NULL,
    leave_days INT NOT NULL,
    leave_start_date DATE NOT NULL,
    leave_end_date DATE NOT NULL,
    last_leave_start_date DATE,
    last_leave_end_date DATE,
    leave_balance INT,
    contact_address VARCHAR(255),
    telephone VARCHAR(30),
    salary_payment VARCHAR(100),
    payment_address VARCHAR(255),
    outside_kenya_permission VARCHAR(10),
    acting_officer VARCHAR(100),
    applicant_date DATE,
    signature VARCHAR(255),
    authority_comments TEXT,
    date DATE,
    authority_signature VARCHAR(255),
    status VARCHAR(20) DEFAULT 'Pending'
);